name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} .
      
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name <YOUR_ACR_NAME>

      - name: Tag Docker image
        run: |
          docker tag myapp:${{ github.sha }} <YOUR_ACR_NAME>.azurecr.io/myapp:${{ github.sha }}

      - name: Push Docker image to Azure Container Registry
        run: |
          docker push <YOUR_ACR_NAME>.azurecr.io/myapp:${{ github.sha }}

      - name: Deploy to Azure Container Instances
        uses: Azure/aci-deploy@v1
        with:
          resource-group: <YOUR_RESOURCE_GROUP>
          name: <YOUR_CONTAINER_GROUP_NAME>
          image: <YOUR_ACR_NAME>.azurecr.io/myapp:${{ github.sha }}
          dns-name-label: <YOUR_DNS_NAME_LABEL>
          location: <YOUR_LOCATION>
          registry-login-server: <YOUR_ACR_NAME>.azurecr.io
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}
          cpu: 1
          memory: 1.5
          ports: 80
