name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} .
      
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name federicoregistry

      - name: Tag Docker image
        run: |
          docker tag myapp:${{ github.sha }} federicoregistry.azurecr.io/myapp:${{ github.sha }}

      - name: Push Docker image to Azure Container Registry
        run: |
          docker push federicoregistry.azurecr.io/myapp:${{ github.sha }}

      - name: Deploy to Azure Container Instances
        uses: Azure/aci-deploy@v1
        with:
          resource-group: containers
          name: web1
          image: federicoregistry.azurecr.io/myapp:${{ github.sha }}
          location: "Canada Central"
          registry-login-server: federicoregistry.azurecr.io
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}
          cpu: 1
          memory: 1.5
          ports: 80
